qx:
  name: qianxun项目
  # 文件路径 示例（ Windows配置D:/ht/uploadPath，Linux配置 /data/ht/uploadPath）
  profile: /data/qianxun/uploadPath
  addressEnabled: false
  captchaType: math

# 优盾支付配置
# 测试环境
bipay:
  #商户号
  merchantId: 301384
  #key为接口授权码APIKEY，由网关分配给商户
  merchantKey: ea9f7435bc2f645fe0f918bcf55c7cef
  #优盾钱包网关香港
  gateway: https://hd01-hk-node.uduncloud.com
  #结果回调网关
  host: http://hotal.asptest.top
  supported-coins: BTC,ETH,TRX

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.ht: debug
    org.springframework: warn
    io.lettuce.core.protocol: error

spring:
  messages:
    basename: i18n/messages
  profiles: 
    active: druid
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: 185.251.45.198
    port: 6379
    database: 0
    password: "tIWdmMdxkpKQXkt9"
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

  mail:
    #服务器
    host: 123.58.177.181
    #邮箱发件人
    username: AsproPlus@vip.163.com
    #授权码
    password: XYVYGAZTACOJZKGW
    properties:
      mail:
        smtp:
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          auth: true
          starttls:
            enable: true
            required: true
    port: 587

token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）（7天=10080分钟）
    expireTime: 10080
  
mybatis:
    typeAliasesPackage: com.qianxun.project.**.domain
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
